trigger: none
pr: none

name: deploy-$(Date:yyyyMMdd)$(Rev:.r)

parameters:
  - name: vm1_enabled
    displayName: 'VM1 - Enabled'
    type: boolean
    default: true
  - name: vm1_os
    displayName: 'VM1 - Operating System'
    type: string
    default: 'Windows'
    values: ['Windows', 'Linux']
  - name: vm1_role
    displayName: 'VM1 - Role'
    type: string
    default: 'jump-client'
    values: ['jump-client', 'jumpoint']
  - name: vm1_install_client
    displayName: 'VM1 - Install PRA Client'
    type: boolean
    default: true
  - name: vm1_create_shortcut
    displayName: 'VM1 - Create PRA Shortcut'
    type: boolean
    default: true
  - name: vm1_protocol
    displayName: 'VM1 - Connection Protocol'
    type: string
    default: 'rdp'
    values: ['rdp', 'ssh', 'vnc']

  - name: vm2_enabled
    displayName: 'VM2 - Enabled'
    type: boolean
    default: true
  - name: vm2_os
    displayName: 'VM2 - Operating System'
    type: string
    default: 'Linux'
    values: ['Windows', 'Linux']
  - name: vm2_role
    displayName: 'VM2 - Role'
    type: string
    default: 'jump-client'
    values: ['jump-client', 'jumpoint']
  - name: vm2_install_client
    displayName: 'VM2 - Install PRA Client'
    type: boolean
    default: true
  - name: vm2_create_shortcut
    displayName: 'VM2 - Create PRA Shortcut'
    type: boolean
    default: true
  - name: vm2_protocol
    displayName: 'VM2 - Connection Protocol'
    type: string
    default: 'ssh'
    values: ['rdp', 'ssh', 'vnc']

  - name: vm3_enabled
    displayName: 'VM3 - Enabled'
    type: boolean
    default: true
  - name: vm3_os
    displayName: 'VM3 - Operating System'
    type: string
    default: 'Windows'
    values: ['Windows', 'Linux']
  - name: vm3_role
    displayName: 'VM3 - Role'
    type: string
    default: 'jumpoint'
    values: ['jump-client', 'jumpoint']
  - name: vm3_install_client
    displayName: 'VM3 - Install PRA Client'
    type: boolean
    default: true
  - name: vm3_create_shortcut
    displayName: 'VM3 - Create PRA Shortcut'
    type: boolean
    default: false
  - name: vm3_protocol
    displayName: 'VM3 - Connection Protocol'
    type: string
    default: 'rdp'
    values: ['rdp', 'ssh', 'vnc']

  - name: vm4_enabled
    displayName: 'VM4 - Enabled'
    type: boolean
    default: false
  - name: vm4_os
    displayName: 'VM4 - Operating System'
    type: string
    default: 'Linux'
    values: ['Windows', 'Linux']
  - name: vm4_role
    displayName: 'VM4 - Role'
    type: string
    default: 'jump-client'
    values: ['jump-client', 'jumpoint']
  - name: vm4_install_client
    displayName: 'VM4 - Install PRA Client'
    type: boolean
    default: true
  - name: vm4_create_shortcut
    displayName: 'VM4 - Create PRA Shortcut'
    type: boolean
    default: true
  - name: vm4_protocol
    displayName: 'VM4 - Connection Protocol'
    type: string
    default: 'ssh'
    values: ['rdp', 'ssh', 'vnc']

  - name: vm5_enabled
    displayName: 'VM5 - Enabled'
    type: boolean
    default: false
  - name: vm5_os
    displayName: 'VM5 - Operating System'
    type: string
    default: 'Windows'
    values: ['Windows', 'Linux']
  - name: vm5_role
    displayName: 'VM5 - Role'
    type: string
    default: 'jump-client'
    values: ['jump-client', 'jumpoint']
  - name: vm5_install_client
    displayName: 'VM5 - Install PRA Client'
    type: boolean
    default: true
  - name: vm5_create_shortcut
    displayName: 'VM5 - Create PRA Shortcut'
    type: boolean
    default: true
  - name: vm5_protocol
    displayName: 'VM5 - Connection Protocol'
    type: string
    default: 'rdp'
    values: ['rdp', 'ssh', 'vnc']

variables:
  - name: azureServiceConnection
    value: 'sc-azure-lab-deploy'
  - name: tfStateResourceGroup
    value: 'rg-terraform-state'
  - name: tfStateStorageAccount
    value: 'stterraformstate001'
  - name: tfStateContainer
    value: 'tfstate'
  - name: vnetResourceGroup
    value: 'rg_sandbox_north_network'
  - name: vnetName
    value: 'vnet_sandbox_north'
  - name: keyVaultName
    value: 'kv-pra-lab-deploy'
  - name: runId
    value: $(Build.BuildNumber)

stages:
  - stage: GenerateManifest
    displayName: 'Stage 1 - Generate Deployment Manifest'
    jobs:
      - job: BuildManifest
        displayName: 'Build manifest.json'
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self
          - task: PowerShell@2
            name: BuildDynamicMatrix
            displayName: 'Build dynamic deployment matrix from VM parameters'
            inputs:
              pwsh: true
              targetType: inline
              script: |
                $ErrorActionPreference = 'Stop'

                $vmDefinitions = @(
                  @{ index = 1; enabled = [System.Convert]::ToBoolean('${{ parameters.vm1_enabled }}'); os = '${{ parameters.vm1_os }}'; role = '${{ parameters.vm1_role }}'; installClient = [System.Convert]::ToBoolean('${{ parameters.vm1_install_client }}'); createShortcut = [System.Convert]::ToBoolean('${{ parameters.vm1_create_shortcut }}'); protocol = '${{ parameters.vm1_protocol }}' },
                  @{ index = 2; enabled = [System.Convert]::ToBoolean('${{ parameters.vm2_enabled }}'); os = '${{ parameters.vm2_os }}'; role = '${{ parameters.vm2_role }}'; installClient = [System.Convert]::ToBoolean('${{ parameters.vm2_install_client }}'); createShortcut = [System.Convert]::ToBoolean('${{ parameters.vm2_create_shortcut }}'); protocol = '${{ parameters.vm2_protocol }}' },
                  @{ index = 3; enabled = [System.Convert]::ToBoolean('${{ parameters.vm3_enabled }}'); os = '${{ parameters.vm3_os }}'; role = '${{ parameters.vm3_role }}'; installClient = [System.Convert]::ToBoolean('${{ parameters.vm3_install_client }}'); createShortcut = [System.Convert]::ToBoolean('${{ parameters.vm3_create_shortcut }}'); protocol = '${{ parameters.vm3_protocol }}' },
                  @{ index = 4; enabled = [System.Convert]::ToBoolean('${{ parameters.vm4_enabled }}'); os = '${{ parameters.vm4_os }}'; role = '${{ parameters.vm4_role }}'; installClient = [System.Convert]::ToBoolean('${{ parameters.vm4_install_client }}'); createShortcut = [System.Convert]::ToBoolean('${{ parameters.vm4_create_shortcut }}'); protocol = '${{ parameters.vm4_protocol }}' },
                  @{ index = 5; enabled = [System.Convert]::ToBoolean('${{ parameters.vm5_enabled }}'); os = '${{ parameters.vm5_os }}'; role = '${{ parameters.vm5_role }}'; installClient = [System.Convert]::ToBoolean('${{ parameters.vm5_install_client }}'); createShortcut = [System.Convert]::ToBoolean('${{ parameters.vm5_create_shortcut }}'); protocol = '${{ parameters.vm5_protocol }}' }
                )

                $matrix = [System.Collections.Generic.List[Object]]::new()
                foreach ($vm in $vmDefinitions) {
                  if (-not $vm.enabled) {
                    continue
                  }

                  $normalizedOs = $vm.os.ToLowerInvariant()
                  if ($normalizedOs -notin @('windows', 'linux')) {
                    throw "VM$($vm.index): unsupported os '$($vm.os)'."
                  }

                  $normalizedRole = $vm.role.ToLowerInvariant()
                  if ($normalizedRole -notin @('jump-client', 'jumpoint')) {
                    throw "VM$($vm.index): unsupported role '$($vm.role)'."
                  }

                  $normalizedProtocol = $vm.protocol.ToLowerInvariant()
                  if ($normalizedOs -eq 'windows' -and $normalizedProtocol -ne 'rdp') {
                    throw "VM$($vm.index): Windows requires protocol 'rdp'."
                  }

                  if ($normalizedOs -eq 'linux' -and $normalizedProtocol -notin @('ssh', 'vnc')) {
                    throw "VM$($vm.index): Linux requires protocol 'ssh' or 'vnc'."
                  }

                  $matrix.Add([PSCustomObject]@{
                      name_prefix     = "vm$($vm.index)-$normalizedOs-$normalizedRole"
                      count           = 1
                      os              = $normalizedOs
                      role            = $normalizedRole
                      distro          = if ($normalizedOs -eq 'linux') { 'ubuntu-24.04' } else { $null }
                      install_client  = $vm.installClient
                      as_jumpoint     = ($normalizedRole -eq 'jumpoint')
                      create_shortcut = $vm.createShortcut
                      protocol        = $normalizedProtocol
                      module_path     = if ($normalizedOs -eq 'windows') { 'infra/terraform/templates/windows_vms_with_public_ip' } else { 'infra/terraform/templates/linux_vms_with_public_ip' }
                      admin_user      = 'LocalAdmin'
                    })
                }

                if ($matrix.Count -eq 0) {
                  throw 'At least one enabled VM is required.'
                }

                $dynamicMatrix = $matrix | ConvertTo-Json -Depth 10 -Compress
                Write-Host "##vso[task.setvariable variable=DynamicMatrix]$dynamicMatrix"
                Write-Host "DynamicMatrix generated with $($matrix.Count) VM definition(s)."
          - task: PowerShell@2
            name: GenerateManifest
            displayName: 'Generate manifest based on deployment matrix'
            inputs:
              filePath: 'automation/scripts/pra_api/generate_manifest.ps1'
              pwsh: true
              arguments: >-
                -RunId "$(runId)"
                -DeploymentMatrixJson '$(DynamicMatrix)'
                -OutputPath "$(Build.ArtifactStagingDirectory)/manifest.json"

          - publish: '$(Build.ArtifactStagingDirectory)/manifest.json'
            artifact: manifest
            displayName: 'Publish manifest artifact'

  - stage: TerraformDeploy
    displayName: 'Stage 2 - Terraform Init & Apply'
    dependsOn: GenerateManifest
    jobs:
      - job: DeployInfrastructure
        displayName: 'Deploy PRA lab infrastructure'
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - download: current
            artifact: manifest
            displayName: 'Download manifest artifact'

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.7.5'

          - task: AzureKeyVault@2
            displayName: 'Load deployment secrets from Key Vault'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              KeyVaultName: '$(keyVaultName)'
              SecretsFilter: 'terraform-admin-password,terraform-linux-ssh-public-key,pra-client-id,pra-client-secret'
              RunAsPreJob: false

          - task: AzureCLI@2
            displayName: 'Terraform init/apply - Windows module'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                set -euo pipefail
                export ARM_CLIENT_ID="$servicePrincipalId"
                export ARM_CLIENT_SECRET="$servicePrincipalKey"
                export ARM_SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
                export ARM_TENANT_ID="$tenantId"

                WINDOWS_CLIENT_COUNT=$(python3 -c "import json,pathlib; manifest=json.loads(pathlib.Path(r'$(Pipeline.Workspace)/manifest/manifest.json').read_text()); print(sum(1 for i in manifest.get('items',[]) if str(i.get('os','')).lower()=='windows' and i.get('install_client') is True))")


                cd infra/terraform/templates/windows_vms_with_public_ip

                terraform init \
                  -backend-config="resource_group_name=$(tfStateResourceGroup)" \
                  -backend-config="storage_account_name=$(tfStateStorageAccount)" \
                  -backend-config="container_name=$(tfStateContainer)" \
                  -backend-config="key=windows-$RUN_ID.tfstate"

                terraform workspace select "$RUN_ID" || terraform workspace new "$RUN_ID"

                terraform apply -auto-approve \
                  -var "run_id=$RUN_ID" \
                  -var "jump_client_count=$WINDOWS_CLIENT_COUNT" \
                  -var "admin_username=LocalAdmin" \
                  -var "vnet_resource_group=$(vnetResourceGroup)" \
                  -var "vnet_name=$(vnetName)"
            env:
              RUN_ID: $(runId)
              TF_VAR_admin_password: $(terraform-admin-password)

          - task: AzureCLI@2
            displayName: 'Terraform init/apply - Linux module'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                set -euo pipefail
                export ARM_CLIENT_ID="$servicePrincipalId"
                export ARM_CLIENT_SECRET="$servicePrincipalKey"
                export ARM_SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
                export ARM_TENANT_ID="$tenantId"

                read -r LINUX_CLIENT_COUNT LINUX_DISTRO < <(python3 -c "import json,pathlib; manifest=json.loads(pathlib.Path(r'$(Pipeline.Workspace)/manifest/manifest.json').read_text()); linux=[i for i in manifest.get('items',[]) if str(i.get('os','')).lower()=='linux' and i.get('install_client') is True]; count=len(linux); distro=(linux[0].get('distro','ubuntu-24.04') if linux else 'ubuntu-24.04'); print(count, distro)")


                cd infra/terraform/templates/linux_vms_with_public_ip

                terraform init \
                  -backend-config="resource_group_name=$(tfStateResourceGroup)" \
                  -backend-config="storage_account_name=$(tfStateStorageAccount)" \
                  -backend-config="container_name=$(tfStateContainer)" \
                  -backend-config="key=linux-$RUN_ID.tfstate"

                terraform workspace select "$RUN_ID" || terraform workspace new "$RUN_ID"

                terraform apply -auto-approve \
                  -var "run_id=$RUN_ID" \
                  -var "jump_client_count=$LINUX_CLIENT_COUNT" \
                  -var "linux_distro=$LINUX_DISTRO" \
                  -var "admin_username=LocalAdmin" \
                  -var "vnet_resource_group=$(vnetResourceGroup)" \
                  -var "vnet_name=$(vnetName)"
            env:
              RUN_ID: $(runId)
              TF_VAR_admin_ssh_public_key: $(terraform-linux-ssh-public-key)

  - stage: ValidateApi
    displayName: 'Stage 3 - API Validation'
    dependsOn: TerraformDeploy
    jobs:
      - job: ValidateClients
        displayName: 'Validate Jump Clients are online'
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self

          - download: current
            artifact: manifest
            displayName: 'Download manifest artifact'

          - task: PowerShell@2
            displayName: 'Run PRA API validation'
            inputs:
              filePath: 'automation/scripts/pra_api/validate_clients_online.ps1'
              pwsh: true
              arguments: >-
                -RunId "$(runId)"
                -ManifestPath "$(Pipeline.Workspace)/manifest/manifest.json"
                -TimeoutMinutes 20
                -PollSeconds 30
            env:
              RUN_ID: $(runId)
              PRA_BASE_URL: $(praBaseUrl)
              PRA_CLIENT_ID: $(pra-client-id)
              PRA_CLIENT_SECRET: $(pra-client-secret)
