trigger: none
pr: none

name: deploy-$(Date:yyyyMMdd)$(Rev:.r)

parameters:
  - name: deployment_matrix
    displayName: Deployment Matrix (server definitions)
    type: object
    default:
      - name_prefix: win-jump-client
        count: 1
        os: windows
        role: jump-client
        distro: null
        install_client: true
        as_jumpoint: false
        create_shortcut: true
        protocol: rdp
      - name_prefix: ubuntu-jump-client
        count: 1
        os: linux
        role: jump-client
        distro: ubuntu-24.04
        install_client: true
        as_jumpoint: false
        create_shortcut: true
        protocol: ssh
      - name_prefix: jumpoint
        count: 1
        os: windows
        role: jumpoint
        distro: null
        install_client: false
        as_jumpoint: true
        create_shortcut: false
        protocol: null

variables:
  - name: azureServiceConnection
    value: 'sc-azure-lab-deploy'
  - name: tfStateResourceGroup
    value: 'rg-terraform-state'
  - name: tfStateStorageAccount
    value: 'stterraformstate001'
  - name: tfStateContainer
    value: 'tfstate'
  - name: vnetResourceGroup
    value: 'rg_sandbox_north_network'
  - name: vnetName
    value: 'vnet_sandbox_north'
  - name: keyVaultName
    value: 'kv-pra-lab-deploy'
  - name: runId
    value: $(Build.BuildNumber)

stages:
  - stage: GenerateManifest
    displayName: 'Stage 1 - Generate Deployment Manifest'
    jobs:
      - job: BuildManifest
        displayName: 'Build manifest.json'
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self

          - task: PowerShell@2
            name: GenerateManifest
            displayName: 'Generate manifest based on deployment matrix'
            inputs:
              filePath: 'scripts/pra_api/generate_manifest.ps1'
              pwsh: true
              arguments: >-
                -RunId "$(runId)"
                -DeploymentMatrixJson '${{ convertToJson(parameters.deployment_matrix) }}'
                -OutputPath "$(Build.ArtifactStagingDirectory)/manifest.json"

          - publish: '$(Build.ArtifactStagingDirectory)/manifest.json'
            artifact: manifest
            displayName: 'Publish manifest artifact'

  - stage: TerraformDeploy
    displayName: 'Stage 2 - Terraform Init & Apply'
    dependsOn: GenerateManifest
    jobs:
      - job: DeployInfrastructure
        displayName: 'Deploy PRA lab infrastructure'
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - download: current
            artifact: manifest
            displayName: 'Download manifest artifact'

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.7.5'

          - task: AzureKeyVault@2
            displayName: 'Load deployment secrets from Key Vault'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              KeyVaultName: '$(keyVaultName)'
              SecretsFilter: 'terraform-admin-password,terraform-linux-ssh-public-key,pra-client-id,pra-client-secret'
              RunAsPreJob: false

          - task: AzureCLI@2
            displayName: 'Terraform init/apply - Windows module'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                set -euo pipefail
                export ARM_CLIENT_ID="$servicePrincipalId"
                export ARM_CLIENT_SECRET="$servicePrincipalKey"
                export ARM_SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
                export ARM_TENANT_ID="$tenantId"

                WINDOWS_CLIENT_COUNT=$(python3 -c "import json; matrix=json.loads('''${{ convertToJson(parameters.deployment_matrix) }}'''); print(sum(int(i.get('count',0)) for i in matrix if str(i.get('os','')).lower()=='windows' and i.get('install_client') is True))")


                cd Terraform_templates/WindowsVMs_with_PublicIP

                terraform init \
                  -backend-config="resource_group_name=$(tfStateResourceGroup)" \
                  -backend-config="storage_account_name=$(tfStateStorageAccount)" \
                  -backend-config="container_name=$(tfStateContainer)" \
                  -backend-config="key=windows-$RUN_ID.tfstate"

                terraform workspace select "$RUN_ID" || terraform workspace new "$RUN_ID"

                terraform apply -auto-approve \
                  -var "run_id=$RUN_ID" \
                  -var "jump_client_count=$WINDOWS_CLIENT_COUNT" \
                  -var "admin_username=LocalAdmin" \
                  -var "vnet_resource_group=$(vnetResourceGroup)" \
                  -var "vnet_name=$(vnetName)"
            env:
              RUN_ID: $(runId)
              TF_VAR_admin_password: $(terraform-admin-password)

          - task: AzureCLI@2
            displayName: 'Terraform init/apply - Linux module'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                set -euo pipefail
                export ARM_CLIENT_ID="$servicePrincipalId"
                export ARM_CLIENT_SECRET="$servicePrincipalKey"
                export ARM_SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
                export ARM_TENANT_ID="$tenantId"

                read -r LINUX_CLIENT_COUNT LINUX_DISTRO < <(python3 -c "import json; matrix=json.loads('''${{ convertToJson(parameters.deployment_matrix) }}'''); linux=[i for i in matrix if str(i.get('os','')).lower()=='linux' and i.get('install_client') is True and int(i.get('count',0))>0]; count=sum(int(i.get('count',0)) for i in linux); distro=(linux[0].get('distro','ubuntu-24.04') if linux else 'ubuntu-24.04'); print(count, distro)")


                cd Terraform_templates/LinuxVMs_with_PublicIP

                terraform init \
                  -backend-config="resource_group_name=$(tfStateResourceGroup)" \
                  -backend-config="storage_account_name=$(tfStateStorageAccount)" \
                  -backend-config="container_name=$(tfStateContainer)" \
                  -backend-config="key=linux-$RUN_ID.tfstate"

                terraform workspace select "$RUN_ID" || terraform workspace new "$RUN_ID"

                terraform apply -auto-approve \
                  -var "run_id=$RUN_ID" \
                  -var "jump_client_count=$LINUX_CLIENT_COUNT" \
                  -var "linux_distro=$LINUX_DISTRO" \
                  -var "admin_username=LocalAdmin" \
                  -var "vnet_resource_group=$(vnetResourceGroup)" \
                  -var "vnet_name=$(vnetName)"
            env:
              RUN_ID: $(runId)
              TF_VAR_admin_ssh_public_key: $(terraform-linux-ssh-public-key)

  - stage: ValidateApi
    displayName: 'Stage 3 - API Validation'
    dependsOn: TerraformDeploy
    jobs:
      - job: ValidateClients
        displayName: 'Validate Jump Clients are online'
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self

          - download: current
            artifact: manifest
            displayName: 'Download manifest artifact'

          - task: PowerShell@2
            displayName: 'Run PRA API validation'
            inputs:
              filePath: 'scripts/pra_api/validate_clients_online.ps1'
              pwsh: true
              arguments: >-
                -RunId "$(runId)"
                -ManifestPath "$(Pipeline.Workspace)/manifest/manifest.json"
                -TimeoutMinutes 20
                -PollSeconds 30
            env:
              PRA_BASE_URL: $(praBaseUrl)
              PRA_CLIENT_ID: $(pra-client-id)
              PRA_CLIENT_SECRET: $(pra-client-secret)
